name: AlfabetaLocal
description: null
flow_name: Alfabeta Scraper End-to-End (Manual Step Confirmation)
entrypoint: flow_main.py:alfabeta_pipeline
work_queue_name: default
tags: []
schedule: null
parameters: {}
infrastructure:
  type: process
  env: {}
  labels: {}
